# this template is for somatic tumor only variant calling using duplex UMIs
# and high coverage panel data
# min_allele_fraction is % i.e. 0.01% = 0.0001
# use_lowfreq_filter: false forces vardict to report all variants,
# including those with low variant frequency
# to report intronic varints use +-200 padded bed file
# for TS data first parse UMIs with:
# bcbio_fastq_umi_prep.py autopair -c 1 --tag1 8 --tag2 8 samplex_1.fq.gz samplex_2.fq.gz,
# where tag1 8 means 8 bp of UMI
# trim_ends trims a spacer between UMI and read
details:
- algorithm:
    aligner: bwa
    align_split_size: false
    correct_umis: /path/config/whitelist.txt
    coverage_interval: regional
    coverage: /path/to/Panel/coverage.bed
    sv_regions: /path/to/Panel/coverage.bed
    variant_regions: /path/to/Panel/variants.bed 
    effects_transcripts: canonical_cancer
    mark_duplicates: true
    min_allele_fraction: 0.01
    variantcaller:
      somatic: vardict
      germline: gatk-haplotype
    platform: Illumina
    quality_format: Standard
    recalibrate: false
    realign: false
    svcaller: [manta, seq2c, cnvkit]
    svprioritize: cancer/az-cancer-panel
    tools_off:
    - gemini
    tools_on: [qualimap_full, damage_filter, gatk4]
    trim_ends: [2,0,2,0]
    variant_regions: panel.bed  
    umi_type: fastq_name
    use_lowfreq_filter: false
  analysis: variant2
  description: samplea
  files:
  - /path/input/sample_a1_1.fq.gz
  - /path/input/sample_a1_2.fq.gz
  genome_build: hg38
  metadata:
    phenotype: tumor
resources:
  fgbio:
    options: [--min-reads, 3]
